secrets:
  FIREBASE_SERVICE_ACCOUNT_JSON:
    file: /home/wahid/git/gcs-key-files/firebase-service-account.json

services:
  api:
    build: ./ai-document-intelligence
    ports:
      - "8081:8081"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/FIREBASE_SERVICE_ACCOUNT_JSON
      OPENAI_ENABLED: true
      R2_ACCESS_KEY: ${R2_ACCESS_KEY}
      R2_SECRET_KEY: ${R2_SECRET_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    secrets:
      - FIREBASE_SERVICE_ACCOUNT_JSON
    depends_on:
      - qdrant
      - ollama

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"

  ollama:
    image: ollama/ollama:latest
    environment:
      OLLAMA_KEEP_ALIVE: -1
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama:
